export { App } from './app.js';
export { getTheme, themes } from './config/themes.js';
export { loadConfig, saveConfig } from './config/loader.js';
export { discoverAgents, getInstalledAgents } from './agents/agent-registry.js';
export { AgentManager } from './agents/agent-manager.js';
export { Orchestrator } from './orchestration/orchestrator.js';
export { ProtocolScanner, buildProtocolInstructions } from './orchestration/protocol.js';
export { TerminalPanel } from './panels/terminal-panel.js';
export { VTerm } from './panels/vterm.js';
export { loadTemplates } from './templates/loader.js';
export type { AgentInfo, AgentType, AgentStatus } from './agents/types.js';
export type { AppConfig, Theme } from './config/types.js';
export type { PromptTemplate } from './templates/types.js';
